# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-28 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_investments',
        ),
        migrations.AddField(
            model_name='preference',
            name='asset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='assets.Asset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='total_investment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
