# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-28 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171028_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='original_investment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
