# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171028_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='transfer_request',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
