# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-28 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_position_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='uninvested',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=15),
            preserve_default=False,
        ),
    ]
