# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_uninvested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='totalInvestment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='uninvested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
